language: go

sudo: false

branches:
  only:
    - master
    - develop

go:
  - 1.6
  - 1.7
  - tip

before_install:
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo
  - go get golang.org/x/tools/cmd/cover

install:
  - go get -v -t ./...

script:
  - go test -v ./... -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - go: tip
