language: go

sudo: false

branches:
  only:
    - master
    - integration

go:
  - 1.6
  - 1.7
  - tip

before_install:
  - bash prepare-aah-env.sh "forge essentials test" "config"

install:
   - go get -v -t aahframework.org/config/...

script:
  - cd $GOPATH/src/aahframework.org/config
  - bash go.test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - go: tip
