language: go

sudo: false

branches:
  only:
    # - master
    # - integration

go:
  - 1.6
  - 1.7
  - 1.8
  - tip

before_install:
  - bash <(curl -s https://aahframework.org/env.txt) "config" "v0"

install:
  - cd $GOPATH/src/aahframework.org/config.v0
  - go get -v -t ./...

script:
  - bash go.test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - go: tip
